# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountIn', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u5165\u5e93\u6570\u91cf')),
            ],
            options={
                'verbose_name': '\u5165\u5e93\u9879',
                'verbose_name_plural': '\u5165\u5e93\u9879',
            },
        ),
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='\u5165\u5e93\u7f16\u53f7')),
                ('c_time', models.CharField(max_length=50, verbose_name='\u5165\u5e93\u65f6\u95f4')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5165\u5e93\u4fe1\u606f')),
            ],
            options={
                'ordering': ['c_time'],
                'verbose_name': '\u5165\u5e93\u8868',
                'verbose_name_plural': '\u5165\u5e93\u8868',
            },
        ),
        migrations.CreateModel(
            name='InventoryMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u8be6\u7ec6\u4fe1\u606f')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u552f\u4e00\u8bc6\u522b\u7801')),
                ('image', models.ImageField(blank=True, default='/photos/americanfootball.jpg', null=True, upload_to='photos', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u7269\u6599',
                'verbose_name_plural': '\u7269\u6599',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=50, verbose_name='\u7269\u6599\u540d\u79f0')),
                ('mAmount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='\u5e93\u5b58\u6570\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='OutItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountOut', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u51fa\u5e93\u6570\u91cf')),
            ],
            options={
                'verbose_name': '\u51fa\u5e93\u9879',
                'verbose_name_plural': '\u51fa\u5e93\u9879',
            },
        ),
        migrations.CreateModel(
            name='OutStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='\u51fa\u5e93\u7f16\u53f7')),
                ('c_time', models.CharField(max_length=50, verbose_name='\u5165\u5e93\u65f6\u95f4')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u51fa\u5e93\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u51fa\u5e93\u8868',
                'verbose_name_plural': '\u51fa\u5e93\u8868',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='\u82f1\u6587\u540d\u79f0')),
                ('feature', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u82f1\u6587\u7b80\u8981\u7279\u5f81')),
                ('uniqueid', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u552f\u4e00\u8bc6\u522b\u7801')),
                ('adate', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u65f6\u95f4\u7f16\u53f7')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u4e2d\u6587\u8be6\u7ec6\u63cf\u8ff0')),
                ('count', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='\u8fdb\u8d27\u4ef7\u683c')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='\u9500\u552e\u4ef7\u683c')),
                ('can_sale', models.BooleanField(default=True, verbose_name='\u53ef\u9500\u552e')),
                ('can_component', models.BooleanField(default=True, verbose_name='\u53ef\u4f5c\u4e3a\u96f6\u4ef6\u7ec4\u5408\u4f7f\u7528')),
                ('image', models.ImageField(blank=True, default='photos/americanfootball_NSqvub1.jpg ', null=True, upload_to='photos', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmAmount', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u4f7f\u7528\u6570\u91cf')),
                ('pmMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.InventoryMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='SKU')),
                ('childAsin', models.CharField(blank=True, max_length=50, null=True, verbose_name='child ASIN')),
                ('title', models.TextField(blank=True, max_length=400, null=True, verbose_name='Title')),
                ('purchasePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u91c7\u8d2d\u4ef7\u683c(rmb)')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='\u5305\u88c5\u91cd\u91cf(kg)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u5305\u88c5\u5c3a\u5bf8\u957f(cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u5305\u88c5\u5c3a\u5bf8\u5bbd(cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u5305\u88c5\u5c3a\u5bf8\u9ad8(cm)')),
                ('volumeWeight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='\u5305\u88c5\u4f53\u79ef\u91cd(kg)')),
                ('dhlShippingFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DHL\u6d77\u8fd0\u8d39(rmb)')),
                ('packageFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u7269\u6599\u8d39(rmb)')),
                ('opFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u8fd0\u8425\u8d39(rmb)')),
                ('currency', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='\u6c47\u7387(us-chn)')),
                ('fbaFullfillmentFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='FBA\u8fd0\u8d39(dollar)')),
                ('shrinkage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u4ea7\u54c1\u635f\u8017(dollar)')),
                ('amazonReferralFee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amazon\u5e73\u53f0\u8d39(%)')),
                ('payoneerServiceFee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Payoneer\u670d\u52a1\u8d39(%)')),
                ('amazonSalePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u552e\u4ef7(dollar)')),
                ('margin', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='\u5229\u6da6(dollar)')),
                ('marginRate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='\u5229\u6da6\u7387(%)')),
                ('productCostPercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='\u4ea7\u54c1\u6210\u672c(%)')),
                ('image', models.ImageField(blank=True, default='/photos/americanfootball.jpg', null=True, upload_to='photos', verbose_name='\u56fe\u7247')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u4e2d\u6587\u5907\u6ce8')),
                ('c_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7ad9\u70b9\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u7ad9\u70b9',
                'verbose_name_plural': '\u7ad9\u70b9',
            },
        ),
        migrations.CreateModel(
            name='Uploadfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6279\u91cf\u4e0a\u4f20\u4eba\u5458')),
                ('date', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('file_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6587\u4ef6\u540d')),
            ],
            options={
                'verbose_name': '\u4e0a\u4f20\u6587\u4ef6\u7ba1\u7406',
                'verbose_name_plural': '\u4e0a\u4f20\u6587\u4ef6\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='\u7537', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4ed3\u5e93\u7f16\u53f7')),
                ('name', models.CharField(max_length=40, verbose_name='\u4ed3\u5e93\u540d\u79f0')),
                ('status', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('location', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u4ed3\u5e93\u5730\u5740')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u76f8\u5173\u4eba\u5458')),
            ],
            options={
                'verbose_name': '\u4ed3\u5e93',
                'verbose_name_plural': '\u4ed3\u5e93',
            },
        ),
        migrations.AddField(
            model_name='producttemp',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u521b\u5efa\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='producttemp',
            name='pMaterial',
            field=models.ManyToManyField(through='login.ProductMaterial', to='login.InventoryMaterial'),
        ),
        migrations.AddField(
            model_name='producttemp',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Site', verbose_name='\u7ad9\u70b9'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='pmProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ProductTemp'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u5165\u5e93\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='userOutstock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u51fa\u5e93\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='outitem',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.OutStock', verbose_name='\u51fa\u5e93\u8868'),
        ),
        migrations.AddField(
            model_name='outitem',
            name='productName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ProductTemp', verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='userPurchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u91c7\u8d2d\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='instock',
            name='userInstock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u5165\u5e93\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='initem',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.InStock', verbose_name='\u5165\u5e93\u8868'),
        ),
        migrations.AddField(
            model_name='initem',
            name='materialName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.InventoryMaterial', verbose_name='\u7269\u6599\u540d\u79f0'),
        ),
    ]
