# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u552f\u4e00\u8bc6\u522b\u7801')),
                ('nickname', models.CharField(max_length=50, verbose_name='\u82f1\u6587\u540d\u79f0')),
                ('feature', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u82f1\u6587\u7b80\u8981\u7279\u5f81')),
                ('adate', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u65f6\u95f4\u7f16\u53f7')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u4e2d\u6587\u8be6\u7ec6\u63cf\u8ff0')),
                ('count', models.PositiveIntegerField(blank=True, max_length=20, null=True, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='\u8fdb\u8d27\u4ef7\u683c')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='\u9500\u552e\u4ef7\u683c')),
                ('can_sale', models.BooleanField(default=True, verbose_name='\u53ef\u9500\u552e')),
                ('can_component', models.BooleanField(default=False, verbose_name='\u53ef\u4f5c\u4e3a\u96f6\u4ef6\u7ec4\u5408\u4f7f\u7528')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u5165\u5e93\u4eba\u5458')),
            ],
            options={
                'ordering': ['-adate'],
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4ed3\u5e93\u7f16\u53f7')),
                ('name', models.CharField(max_length=40, verbose_name='\u4ed3\u5e93\u540d\u79f0')),
                ('status', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('location', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u4ed3\u5e93\u5730\u5740')),
                ('users', models.ManyToManyField(blank=True, null=True, to='login.User', verbose_name='\u76f8\u5173\u4eba\u5458')),
            ],
            options={
                'verbose_name': '\u4ed3\u5e93',
                'verbose_name_plural': '\u4ed3\u5e93',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Warehouse', verbose_name='warehouse'),
        ),
    ]
