# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-23 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outitem',
            name='dhlshippingfeeInput',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='dhl\u6d77\u8fd0\u8d39'),
        ),
        migrations.AddField(
            model_name='outitem',
            name='siteinput',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7ad9\u70b9'),
        ),
        migrations.AddField(
            model_name='outitem',
            name='totalfee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u8fd0\u8d39\u5408\u8ba1'),
        ),
    ]
