# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190123_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u5e93\u5b58\u6570\u91cf'),
        ),
    ]
