# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-23 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190323_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemp',
            name='dhlShippingFee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='DHL\u6d77\u8fd0\u8d39(rmb)'),
        ),
    ]
