# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190123_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='users',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u76f8\u5173\u4eba\u5458'),
        ),
    ]
