# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-24 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190323_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemp',
            name='adcost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u5e7f\u544a\u8d39(dollar)'),
        ),
    ]
