# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190123_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='can_component',
            field=models.BooleanField(verbose_name='\u53ef\u4f5c\u4e3a\u96f6\u4ef6\u7ec4\u5408\u4f7f\u7528'),
        ),
    ]
