# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190324_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='operation time')),
                ('act', models.CharField(blank=True, max_length=200, null=True, verbose_name='act')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='user')),
            ],
        ),
    ]
