# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_product_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='image',
        ),
    ]
