# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190126_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='photos/americanfootball_NSqvub1.jpg ', null=True, upload_to='photos', verbose_name='\u56fe\u7247'),
        ),
    ]
