# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_autolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autolog',
            name='act',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u64cd\u4f5c\u884c\u4e3a'),
        ),
        migrations.AlterField(
            model_name='autolog',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='autolog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u7528\u6237\u540d'),
        ),
    ]
