# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190327_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autolog',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
    ]
