# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190327_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autolog',
            options={'verbose_name': '\u65e5\u5fd7', 'verbose_name_plural': '\u65e5\u5fd7'},
        ),
        migrations.AlterModelOptions(
            name='producttemp',
            options={'verbose_name': '\u4ea7\u54c1', 'verbose_name_plural': '\u4ea7\u54c1'},
        ),
        migrations.AlterModelOptions(
            name='uploadfiles',
            options={'verbose_name': '\u4e0a\u4f20\u6587\u4ef6\u5386\u53f2\u8bb0\u5f55', 'verbose_name_plural': '\u4e0a\u4f20\u6587\u4ef6\u5386\u53f2\u8bb0\u5f55'},
        ),
    ]
