# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-24 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190329_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u65f6\u95f4')),
                ('message', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u62a5\u9519\u4fe1\u606f')),
                ('page', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u9875\u9762')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u62a5\u9519\u65e5\u5fd7',
                'verbose_name_plural': '\u62a5\u9519\u65e5\u5fd7',
            },
        ),
    ]
