# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-30 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190425_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outitem',
            name='totalfee',
        ),
        migrations.AddField(
            model_name='outitem',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='\u5305\u88c5\u4f53\u79ef(m3)'),
        ),
        migrations.AddField(
            model_name='outitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='\u5305\u88c5\u91cd\u91cf(kg)'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='tag_done',
            field=models.BooleanField(default=False, verbose_name='\u5165\u5e93\u6807\u5fd7'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='tag_pre',
            field=models.BooleanField(default=False, verbose_name='\u9884\u5165\u5e93\u6807\u5fd7'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='total_freightfee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='\u603b\u8fd0\u8d39(rmb)'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='total_volume',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='\u603b\u4f53\u79ef(m3)'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='\u603b\u91cd\u91cf(kg)'),
        ),
        migrations.AlterField(
            model_name='outitem',
            name='dhlshippingfeeInput',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='dhl\u8fd0\u8d39'),
        ),
    ]
