# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190501_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOutitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u9884\u51fa\u5e93\u6570\u91cf')),
            ],
            options={
                'verbose_name': '\u9884\u51fa\u5e93\u9879',
                'verbose_name_plural': '\u9884\u51fa\u5e93\u9879',
            },
        ),
        migrations.CreateModel(
            name='PreOutstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=50, verbose_name='\u9884\u51fa\u5e93\u7f16\u53f7')),
                ('ptime', models.CharField(max_length=50, verbose_name='\u7f16\u8f91\u65f6\u95f4')),
                ('pdescription', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='\u603b\u91cd\u91cf(kg)')),
                ('total_volume', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='\u603b\u4f53\u79ef(m3)')),
                ('total_freightfee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='\u603b\u8fd0\u8d39(rmb)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='\u64cd\u4f5c\u4eba\u5458')),
            ],
            options={
                'verbose_name': '\u9884\u51fa\u5e93\u8868',
                'verbose_name_plural': '\u9884\u51fa\u5e93\u8868',
            },
        ),
        migrations.AddField(
            model_name='outitem',
            name='site',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7ad9\u70b9'),
        ),
        migrations.AddField(
            model_name='preoutitem',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.PreOutstock', verbose_name='\u9884\u51fa\u5e93\u8868'),
        ),
        migrations.AddField(
            model_name='preoutitem',
            name='productName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ProductTemp', verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
    ]
