# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20190501_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaterial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='\u91c7\u8d2d\u4ef7(rmb)'),
        ),
    ]
