# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_inventorymaterial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaterial',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5e93\u5b58\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mAmount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5e93\u5b58\u6570\u91cf'),
        ),
    ]
